### ISSUE TITLE
How to write lookup table

### ISSUE THREAD

**Issue by richardjgowers** [BIOS-IMASL/chesweet#18]
This is related to the JOSS review at openjournals/joss-reviews#488

Re this point:
Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

I couldn't find documentation for how to write lookup tables yourself, ie what's the format required for these files

Slightly related, the tables included would benefit from a header line explaining what the columns all are, rather than having to consult the code to see how they're read/used to figure this out

**Comment by PabloGGaray** [comment]
Hi @richardjgowers, we made the changes that you suggested in this Issue and in the Issues #15, #16 and #17. Let us know if these changes are according to your suggestions.
